myapp/urls.py
from django.conf.urls import url, include
from .views import index, tambahstatus, profil, book, subscribe, data_json, add_subscriber, check_valid, login, logout_view

#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'tambahstatus', tambahstatus, name='tambahstatus'),
    url(r'^profil', profil, name = 'profil'),
    url(r'^book', book, name = 'book'),
    url(r'^subscribe', subscribe, name='subscribe'),
    url(r'^data_json', data_json, name = 'data_json'),
    url(r'^check_valid/', check_valid, name='check_valid'),
    url(r'^add_subscriber/', add_subscriber, name='add_subscriber'),
    url(r'^login', login, name='login'),
    url(r'^logout/', logout_view, name='logout'),

]

myproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('myapp.urls', 'myapp'), namespace='myapp')),
]

myapp/models.py
from django.conf import settings
from django.db import models
from django.core.validators import MinLengthValidator

# Create your models here.
class status(models.Model):
	deskripsi = models.TextField(max_length=300)
	tanggal = models.DateTimeField(auto_now_add=True)

class Subscribe(models.Model):
	email = models.EmailField(error_messages={'unique': 'An account with this email exist.'})
	nama = models.CharField(max_length = 50)
	password = models.CharField(validators=[MinLengthValidator(4)], max_length = 20)

myapp/forms.py
from django import forms

class status_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }

    deskripsi_attrs = {
        'type': 'text',
        'placeholder':'Apa yang anda pikirkan...'
    }

    deskripsi = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=deskripsi_attrs))

class Subscribe_Form(forms.Form):
	nama_attrs = {
		'id' : 'id_nama',
        'type': 'text',
        'class': 'form-control',
        'placeholder':'Name'
    }
	email_attrs = {
		'id' : 'id_email',
        'type': 'email',
        'class': 'form-control',
        'placeholder':'Email'
    }
	pass_attrs = {
		'id' : 'id_password',
        'type': 'password',
        'class': 'form-control',
        'placeholder':'Password',
		'required pattern' : '[a-zA-Z0-9]+',
		'title' : 'Harus Alpha Numeric'
    }
	email = forms.EmailField(widget=forms.TextInput(attrs=email_attrs))
	nama = forms.CharField(widget=forms.TextInput(attrs=nama_attrs))
	password = forms.CharField(min_length = 8 ,widget=forms.TextInput(attrs=pass_attrs))

myapp/views.py
from django.http import HttpResponseRedirect, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from .forms import status_Form, Subscribe_Form
from .models import status, Subscribe
from django.shortcuts import render
import requests

# Create your views here.
response={}

def index(request):
    response['stats'] = status_Form
    response['status'] = status.objects.all()
    html = 'index.html'
    return render(request, html, response)

def tambahstatus(request):
    form = status_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['deskripsi'] = request.POST['deskripsi']
        a = status(deskripsi=response['deskripsi'])
        a.save()
        return HttpResponseRedirect('/')
    else:
        return HttpResponseRedirect('/')

#------------------------------------------------------------------------------------------		

def profil(request):
	return render(request, 'profil.html')

#------------------------------------------------------------------------------------------

def book(request):
    return render(request, 'book.html')
    
def data_json(request):
    search_data = request.GET.get("search_field")
    search = "https://www.googleapis.com/books/v1/volumes?q=" + str(search_data)
    my_list = requests.get(search)
    json = my_list.json()
    return JsonResponse(json)

#-------------------------------------------------------------------------------------------

def subscribe(request):
    forms = Subscribe.objects.all()
    response = {'form' : Subscribe_Form, 'result': forms}
    return render(request, 'subscribe.html', response)

def add_subscriber(request):
    response = {}
    if (request.method == "POST" or None):
        response['email'] = request.POST['email']
        response['nama'] = request.POST['nama']
        response['password'] = request.POST['password']
        subscriber = Subscribe(email = response['email'], nama = response['nama'], password = response['password'])
        subscriber.save()
    return JsonResponse({})

def check_valid(request):
    email = request.POST.get('email', None)
    data = {
        'is_taken': Subscribe.objects.filter(email=email).exists()
    }
    return JsonResponse(data)

#------------------------------------------------------------------------------------------     

def login(request):
    return render(request, 'login.html')

def login_view(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username = username, password = password)
    if user is not None:
        request.session['user_login'] = username
        res =  HttpResponseRedirect('status:book')
        res.set_cookie('test', 'berhasil')
        res.set_cookie('username', username)
    else:
        return HttpResponseRedirect('/login')
        
def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/book')

myapp/templates/book.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>Graciela Chika Putri</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link href="{%static 'MyProfile/style.css'%}" rel="stylesheet" type="text/css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <script src="{%static 'loading.js'%}"></script>
        <script src="{%static 'MyProfile/myprofile.js'%}"></script>
    </head>

<body onload="myFunction()" style="margin: 0;">
    <div id="loader"></div>
    <div style="display: none;" id="myDiv" class="animate-bottom">
       <div class = "mycontent">
            <div class="jumbotron">
                <h2 style="font-size:300%; text-align: center">My Book</h2>
            </div>
    
            <div class = "container">
                <h2 id= "jumlahBuku" style = "text-align: center"> My Favorite Book
                    <i class='fa fa-star'style = 'color : yellow'> </i>
                </h2>
                <table class = "table-responsive table table-hover table table-stripped" id = "tableBuku"> 
                </table>
            </div>
        </div>
        <br><br><br>
            <a href="tambahstatus.html">
                <button>Tambah Status</button>
            </a>    
            <a href="profil.html">
                <button>Profil</button>
            </a>    
            <a href="subscribe.html">
                <button>Subscribe</button>
            </a>
            <a href="login.html">
                <button>Login</button>
            </a>
    </div>
</body>
</html>

myapp/templates/index.html
<!DOCTYPE html>
<html>
<head>
<title>Story6_GracielaChikaPutri</title>
</head>
<body style="background-color:#F36546;">
<h1 class="main-title">Hello, Apa kabar?</h1>
<hr/>

<div class="container">
    <a href="profil.html">
        <button>Profil</button>
    </a>
    <a href="book.html">
        <button>Book</button>
    </a>
    <a href="subscribe.html">
        <button>Subscribe</button>
    </a>
    <a href="login.html">
        <button>Login</button>
    </a>

    <form id="form" method="POST" action="{% url 'myapp:tambahstatus' %}">
        <h2>Masukkan status</h2>
        {% csrf_token %}
        {{ stats }}
        <input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Submit">
        <br>
    </form>
</div>


<div style="margin: 5% 5%">
    <h2>My Status</h2>
    <div style = "width: 80%">
        <table class="table" border="#0000" style="width: 100%">
            <tr background-color="#ffff">
            <th style="width: 40%">Status</th>
            <th style="width: 60%">Tanggal</th>
           </tr>
           {%for e in status%}
           <tr background-color=#ffff>
            <td>{{e.deskripsi}}</td>
            <td>{{e.tanggal}}</td>
           </tr>
           {%endfor%}
        </table>
    </div>
</div>

</body>

</html>

myapp/templates/login.html
{% load static %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <title>Graciela Chika Putri</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <script src="{%static 'js10.js'%}"></script>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link href="{%static 'MyProfile/style.css'%}" rel="stylesheet" type="text/css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <script src="{%static 'loading.js'%}"></script>
    </head> 

<body onload="myFunction()" style="margin: 0;">
    <div id="loader"></div>
    <div style="display: none;" id="myDiv" class="animate-bottom">

    <div class = "mycontent">
        <div class="jumbotron">
            <h1 style="font-size : 50px" > Hello, Apa kabar? </h1>
        </div>
        <div class="container">
            <a href="index.html">
                <button>Status</button>
            </a>
            <a href="profil.html">
                <button>Profil</button>
            </a>
            <a href="book.html">
                <button>Book</button>
            </a>
            <a href="subscribe.html">
                <button>Subscribe</button>
            </a>
        <br>

        <section>
            <div class="row">
                <div class = "col-md-3">
                </div>
                <div class="col-md-6 col-md-offset-6">
                    <div class="form-regis">
                        <form id="form" method="POST" action = "{% url 'myapp:login' %}">
                            {% csrf_token %}
                            Username:<br>
                            <input type="text" name="username"><br>
                            Password:<br>
                            <input type="password" name="password"><br><br>
                            <input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Submit">
                            <br>
                        </form>
                    </div>
                </div>
            </div>
        </section>
    </div>   
</body>
</html>

myapp/templates/profil.html
{% load staticfiles %}
{% load static %}

<!DOCTYPE html>
<html>
	<head>
		<title>Graciela Chika Putri</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
		<link href="{%static 'MyProfile/style.css'%}" rel="stylesheet" type="text/css">
		<link href="{%static 'css/styl10.css'%}" rel="stylesheet" type="text/css">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
		<script src="{%static 'loading.js'%}"></script>
		<script src="{%static 'MyProfile/myprofile.js'%}"></script>
		<script src="{%static 'MyProfile/js10.js'%}"></script>
		<script src="{%static 'MyProfile/vendor/jquery.js'%}"></script>
		<script src="{%static 'MyProfile/vendor/what-input.js'%}"></script>
		<script src="{%static 'MyProfile/vendor/foundation.js'%}"></script>
	</head>
	
	<body onload="myFunction()" style="margin: 0;">
		<div id="loader"></div>
		<div style="display: none;" id="myDiv" class="animate-bottom">
		<div class = "jumbotron">
			<img src = "https://scontent.fcgk12-1.fna.fbcdn.net/v/t1.0-9/33147992_1508943735899972_6159831298375417856_n.jpg?_nc_cat=110&_nc_eui2=AeFFsbDIImIUM1YqrKIBXvDFn27KStXl-Z2j13WVaU4XeyROP5A2sJxfU6y0GpjS5WtUf14dRdCbcZmgCqo4VKUgvYmn1IDM3RQE28ZeaqmItQ&oh=2c5907ac39548f3da844c1b6e594c39e&oe=5C315A9A">
		</div>

    	<a href="tambahstatus.html">
        	<button>Tambah Status</button>
    	</a>	
		<a href="book.html">
        	<button>Book</button>
    	</a>	
		<a href="subscribe.html">
        	<button>Subscribe</button>
    	</a>
    	<a href="login.html">
        	<button>Login</button>
    	</a>
    	<br><br>

		<div class = "container">
			<button type="button" class="btn btn-info">Bisa Ganti Tema loohh!</button>
			<h1 id = "kotak" style="font-size: 20px">Aktivitas Saya</h1>
			<div id = "panel">
				<ul>
                	<li>Makan</li>
                	<li>Tidur</li>  
                	<li>Kuliah</li> 
                	<li>Rapat</li>
                	<br>
            	</ul>
			</div>

			<h1 id = "kotak2" style="font-size: 20px">Pengalaman Berorganisasi</h1>
			<div id = "panel2">
				<ul>
                	<br>
                	<li>Panitia Natal KMK UI</li>
                	<li>SENBUD DEM FASILKOM UI</li>  
                	<li>PEMIRA FASILKOM UI 2017</li>
                	<br>
            	</ul>
			</div>

			<h1 id = "kontak3" style="font-size: 20px">Prestasi</h1>
			<div id = "panel3">
				<ul>
                	<br>
                	<li>haha</li>
                	<li>haha</li>  
                	<li>haha</li> 
                	<li>haha</li>
                	<br>
            	</ul>
			</div>
		</div>

		<script>
			var myVar;

			function myFunction() {
    			myVar = setTimeout(showPage, 3000);
			}

			function showPage() {
  				document.getElementById("loader").style.display = "none";
  				document.getElementById("myDiv").style.display = "block";
			}
		</script>
	</div>
</body>
</html>

myapp/templates/subscribe.html
{% load static %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <title>Graciela Chika Putri</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <script src="{%static 'js10.js'%}"></script>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link href="{%static 'MyProfile/style.css'%}" rel="stylesheet" type="text/css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <script src="{%static 'loading.js'%}"></script>
    </head> 

<body onload="myFunction()" style="margin: 0;">
    <div id="loader"></div>
    <div style="display: none;" id="myDiv" class="animate-bottom">
    
    <div class = "mycontent">
        <div class="jumbotron">
            <h2 style="font-size:300%; text-align: center">Subscribe Registration</h2>
        </div>

        <a href="tambahstatus.html">
            <button>Tambah Status</button>
        </a>    
        <a href="profil.html">
            <button>Profil</button>
        </a>
        <a href="book.html">
            <button>Book</button>
        </a>
        <a href="login.html">
            <button>Login</button>
        </a>
        <br><br>
        
        <section>
            <div class="row">
                <div class = "col-md-3">
                </div>
                <div class="col-md-6 col-sm-6">
                    <div class="form-regis">
                        <form id="form" method="POST" action = "{% url 'myapp:add_subscriber' %}">
                            <br><br>
                            {% csrf_token %}
                            {{form}}
                            <br>
                            <input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Submit">
                            <br>
                        </form>
                    </div>
                </div>
            </div>
        </section>

        <div class="container">
            <div class="modal" id="myModal">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <!-- Modal Header -->
                        <div class="modal-header">
                            <h4 class="modal-title">SUKSES !</h4>
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                        </div>
    
                        <!-- Modal body -->
                        <div class="modal-body">
                            Data anda berhasil tersimpan ...
                        </div>
    
                        <!-- Modal footer -->
                        <div class="modal-footer">
                            <button type="button" class="btn btn-success" data-dismiss="modal">Close</button>
                        </div>
    
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>